// <auto-generated />
using DesafioBackEnd.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioBackEnd.Data.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200819221532_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:IdentityIncrement", 1)
                .HasAnnotation("SqlServer:IdentitySeed", 1)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioBackEnd.Data.Models.EspecialidadeMedido", b =>
                {
                    b.Property<int>("IdMedico")
                        .HasColumnName("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecialidade")
                        .HasColumnName("IdEspecialidade")
                        .HasColumnType("int");

                    b.HasKey("IdMedico", "IdEspecialidade")
                        .HasName("PFK_EspecialidadeMedico");

                    b.HasIndex("IdEspecialidade");

                    b.ToTable("EspecialidadeMedico");
                });

            modelBuilder.Entity("DesafioBackEnd.Models.Especialidade", b =>
                {
                    b.Property<int>("IdEspecilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdEspecialidade")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeEspecialidade")
                        .IsRequired()
                        .HasColumnName("NomeEspecialidade")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("IdEspecilidade")
                        .HasName("IdEspecialidade");

                    b.ToTable("Especialidade");
                });

            modelBuilder.Entity("DesafioBackEnd.Models.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdMedico")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnName("CRM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMedico")
                        .IsRequired()
                        .HasColumnName("NomeMedico")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("IdMedico")
                        .HasName("IdMedico");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("DesafioBackEnd.Data.Models.EspecialidadeMedido", b =>
                {
                    b.HasOne("DesafioBackEnd.Models.Especialidade", "Especialidade")
                        .WithMany("EspecialidadeMedicos")
                        .HasForeignKey("IdEspecialidade")
                        .HasConstraintName("FK_EspecialidadeEspecialidadeMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesafioBackEnd.Models.Medico", "Medico")
                        .WithMany("EspecialidadeMedicos")
                        .HasForeignKey("IdMedico")
                        .HasConstraintName("FK_MedicoEspecialidadeMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
